schoolcontact_formation_homepage:
    pattern:  /
    defaults: { _controller: SchoolcontactFormationBundle:Formation:index }

schoolcontact_annuaire_homepage:
    pattern:  /annuaire
    defaults: { _controller: SchoolcontactFormationBundle:Formation:annuaire }
schoolcontact_annuaire_ajax_ville:
    pattern:  /ajax/ville/{id}
    defaults: { _controller: SchoolcontactFormationBundle:Formation:ajaxVilleId }


schoolcontact_formation_geographique_region:
    pattern: /region/{slug}
    defaults: { _controller: SchoolcontactFormationBundle:Formation:listFormationRegion }

schoolcontact_formation_geographique_departement:
    pattern: /departement/{slug}
    defaults: { _controller: SchoolcontactFormationBundle:Formation:listFormationDepartement }

schoolcontact_formation_all:
    pattern: /all-formations
    defaults: { _controller: SchoolcontactFormationBundle:Formation:listFormation }

schoolcontact_formation_view:
    pattern: /formation/{id}
    defaults: { _controller: SchoolcontactFormationBundle:Formation:viewFormation }



schoolcontact_connecte_homepage:
    pattern:  /consulter
    defaults: { _controller: SchoolcontactFormationBundle:Formation:consulter }
schoolcontact_messagerie_homepage:
    pattern:  /messagerie
    defaults: { _controller: SchoolcontactFormationBundle:Formation:messagerie }
schoolcontact_gestion_homepage:
    pattern:  /gestion
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestion }
gestionecole:
    pattern:  /gestion/ecole
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestionecole }
gestionusers:
    pattern:  /gestion/users
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestionusers }
gestionformation:
    pattern:  /gestion/formation
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestionformation }
schoolcontact_inscription_ecole:
    pattern:  /inscriptionEcole
    defaults: { _controller: SchoolcontactFormationBundle:Formation:inscriptionecole }
monCompte:
    pattern:  /monCompte
    defaults: { _controller: SchoolcontactFormationBundle:Formation:moncompte }
contact:
    pattern:  /contact
    defaults: { _controller: SchoolcontactFormationBundle:Formation:contact }
accueil:
    pattern:  /accueil
    defaults: { _controller: SchoolcontactFormationBundle:Formation:accueil }
visite:
    pattern:  /visite
    defaults: { _controller: SchoolcontactFormationBundle:Formation:visite }
