schoolcontact_formation_homepage:
    pattern:  /
    defaults: { _controller: SchoolcontactFormationBundle:Formation:index }
schoolcontact_connecte_homepage:
    pattern:  /consulter
    defaults: { _controller: SchoolcontactFormationBundle:Formation:consulter }
schoolcontact_messagerie_homepage:
    pattern:  /messagerie
    defaults: { _controller: SchoolcontactFormationBundle:Formation:messagerie }
schoolcontact_gestion_homepage:
    pattern:  /gestion
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestion }
gestionecole:
    pattern:  /gestion/ecole
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestionecole }
gestionusers:
    pattern:  /gestion/users
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestionusers }
gestionformation:
    pattern:  /gestion/formation
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestionformation }
schoolcontact_inscription_ecole:
    pattern:  /inscriptionEcole
    defaults: { _controller: SchoolcontactFormationBundle:Formation:inscriptionecole }
monCompte:
    pattern:  /monCompte
    defaults: { _controller: SchoolcontactFormationBundle:Formation:moncompte }
contact:
    pattern:  /contact
    defaults: { _controller: SchoolcontactFormationBundle:Formation:contact }