schoolcontact_formation_homepage:
    pattern:  /
    defaults: { _controller: SchoolcontactFormationBundle:Formation:index }
schoolcontact_connecte_homepage:
    pattern:  /consulter
    defaults: { _controller: SchoolcontactFormationBundle:Formation:consulter }
schoolcontact_messagerie_homepage:
    pattern:  /messagerie
    defaults: { _controller: SchoolcontactFormationBundle:Formation:messagerie }
schoolcontact_gestion_homepage:
    pattern:  /gestion
    defaults: { _controller: SchoolcontactFormationBundle:Formation:gestion }