#FosUserBundle Routes
fos_user_security:
    resource: "routing/security.yml"

fos_user_profile:
    resource: "routing/profile.yml"
    prefix: /compte

fos_user_register:
    resource: "routing/registration.yml"
    prefix: /inscription

fos_user_resetting:
    resource: "routing/resetting.yml"
    prefix: /resetting

fos_user_change_password:
    resource: "routing/change_password.yml"
    prefix: /compte

fos_user_group:
    resource: "routing/group.yml"
    prefix: /groupe

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connexion

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connexion

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connexion

facebook_login:
    pattern: /connexion/check-facebook

twitter_login:
    pattern: /connexion/check-twitter