parameters:
    my_user_provider.class: Schoolcontact\UserBundle\Security\User\Provider\FOSUBUserProvider

services:
    my_user_provider:
        class: %my_user_provider.class%
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, twitter: twitter_id}]