security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_FACEBOOK   
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_FACEBOOK]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path:           fos_user_security_login
                check_path:           fos_user_security_check
                provider:             fos_userbundle
                csrf_provider:        form.csrf_provider

            logout:
                path:                 fos_user_security_logout
                target:               /

            anonymous:                true

            oauth:
                resource_owners:
                    facebook:         "/connexion/check-facebook"
                    twitter:          "/connexion/check-twitter"
                login_path:           fos_user_security_login
                failure_path:         fos_user_security_check

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service:          my_user_provider

        login:
            pattern:                  ^/connexion$
            security:                 false

            remember_me:
                key:                  "%secret%"
                lifetime:             31536000 # 365 days in seconds
                path:                 /
                domain:               ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
