security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_FACEBOOK   
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_FACEBOOK]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        my_fos_facebook_provider:
            id: my.facebook.user # Notre provider, nous y viendrons par la suite.

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path:          fos_user_security_login
                use_forward:         true
                check_path:          fos_user_security_check
                failure_path:        null
                default_target_path: /
                remember_me:         true
                provider:            fos_userbundle
                csrf_provider:       form.csrf_provider

            remember_me:
                key:                 %secret%
                lifetime:            300000
                path:                /
                domain:              ~

            logout:
                path:                fos_user_security_logout
                target:              /

            anonymous:               true

            fos_facebook:
                app_url:             "%api_facebook_name%"
                server_url:          "%api_facebook_server%"
                login_path:          fos_user_security_login
                check_path:          facebook_security_check
                default_target_path: /
                provider:            my_fos_facebook_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
